//
//  ServiceNameConstants.swift
//  Finca
//
//  Created by harsh panchal on 12/06/19.
//  Copyright © 2019 anjali. All rights reserved.
//

import Foundation

public struct ServiceNameConstants {
    
    
    public static let LOCATION_CONTROLLER_ENC = "location_controller_enc.php"
    
    public static let LOCATION_CONTROLLER = "location_controller_new.php"
    public static let PENALTY_CONTROLLER = "penaltyController.php"
    public static let SLIDER_CONTROLLER = "get_slider_controller.php"
    public static let BILL_CONTROLLER = "bill_controller.php"
    public static let MAINTAINANCE_CONTROLLER = "maintenance_controller_new.php"
    public static let API_KEY = "bmsapikey"
    public static let VISITOR_CONTROLLER = "user_visitor_controller.php"
    public static let login = "resident_login_controller.php"
    public static let societyList = "society_list_controller.php"
    public static let blockList = "block_list_controller.php"
    public static let residentRegisterController = "resident_register_controller.php"
    public static let blockListController = "block_list_controller.php"
    public static let chatController = "chat_controller.php"
    public static let getParkingDetailController = "get_parking_detail_controller.php"
    public static let employeeTypeController = "employee_type_controller.php"
    public static let employeeListController = "employee_list_controller.php"
    public static let userNotificationController = "user_notification_controller.php"
    public static let galleryController = "get_event_gallery_controller.php"
    public static let documentController = "document_controller.php"
    public static let dailynewscontroller = "daily_news_controller.php"
    public static let renewplancontroller = "renew_plan_controller.php"
    public static let electionController = "get_election_controller.php"
    public static let complainController = "resident_complain_controller.php"
    public static let pollingController = "voting_list_controller.php"
    public static let maintenanceController = "maintenance_controller.php"
    public static let getUserPaymentData = "get_user_payment_data.php"
    public static let residentDataUpdateController = "resident_data_update_controller.php"
    public static let switchController = "switch_controller.php"
    public static let switchUserController = "switch_user_controller.php"
    public static let forgotPassword = "forgot_password.php"
    public static let userEventController = "user_event_controller.php"
    public static let buildingDetailsController = "buildingDetails_controller.php"
    public static let emergencyNumberController = "emergency_numbber_list_controller.php"
    public static let balanceSheetController  = "balancesheet_controller.php"
    public static let getFacilityController = "get_facility_controller.php"             // get_facility_controller.php
    public static let getMyFacilityController = "get_my_facility_controller.php"
    public static let user_notification_controller = "user_notification_controller.php"
    
    // public static let getSOS_events_controller  = "getSOS_events_controller.php"
    public static let resident_sos_controller  = "resident_sos_controller.php"
    public static let vehicle_controller  = "vehicle_controller.php"
    
    public static let feedback_mail_controller  = "feedback_mail_controller.php"
    public static let version_controller  = "version_controller_ios.php"
    //    public static let version_controller  = "test_controller.php"
    public static let check_login_status  = "check_login_status.php"
    public static let aboutController  = "aboutController.php"
    public static let appMenuController  = "app_menu_controller.php"
    public static let resident_data_update_controller2  = "resident_data_update_controller.php"
    public static let profesional_detail_controller  = "profesional_detail_controller.php"
    public static let newsFeedController = "news_feed_controller.php"
    public static let newsFeedControllerNew = "news_feed_controller_new.php"
    public static let newsFeedControllerEdit = "news_feed_controller.php"
    public static let LSPController = "local_service_provider_controller.php"
    public static let noticeBoardController = "noticeBoardController.php"
    public static let contactFincasysTeam = "contact_fincasysteam_controller.php"
    public static let chat_delete_controller = "chat_controller.php"
    public static let chat_controller_group = "chat_controller_group.php"
    public static let payuController = "payumoney_controller.php"
    public static let rent_sale_controller = "rent_sale_controller.php"
    public static let otp_controller = "otp_controller_new.php"
    public static let scheduleController = "employee_schedule_controller.php"
    public static let lostAndFoundController = "lost_found_controller.php"
    public static let violencecontroller = "violence_controller.php"
    
    // public static let memberParkingController = "view_parking_list_controller_new.php"
    
    public static let memberParkingController = "view_parking_list_controller_new1.php"
    
    //    public static let m"contact_fincasysteam_controller.php"
    public static let occupationController = "profesional_detail_controller.php"
    public static let bussinessCategoryController = "businessCategoryController.php"
    public static let CreateGroupController = "create_group_controller.php"
    public static let parkingController = "parking_controller.php"
    public static let employee_attendence_controller = "employee_attendence_controller.php"
    public static let requestController = "requests_controller.php"
    public static let classifiedController = "classified_controller.php"
    public static let dailyVisiterController = "user_visitor_controller.php"
    public static let offerstoreController = "stores_list"
    public static let offerCategoryController = "category_list"
    public static let storeOffers = "store_offers"
    public static let  categoryOffers = "category_offers"
    public static let surveyController = "survey_controller.php"
    //public static let emojiController = "emoji_response.json"
    public static let housie_controller = "housie_controller.php"
    public static let finBookController = "fin_book_controller.php"
    public static let discussionController = "discussion_controller.php"
    public static let childSecurityController = "child_security_controller.php"
    public static let myActivityController = "myactivity_controller.php"
    public static let kbgController = "kbg_controller.php"
    public static let tenant_controller = "tenant_controller.php"
    public static let visitor_Parking_Controller = "view_parking_list_controller_new1.php"
    public static let payumoney_maintenace_controller = "payumoney_maintenace_controller.php"
    public static let family_controller = "family_controller.php"
    public static let commercial_portal_controller = "commercial_portal_controller.php"
    public static let payment_controller = "payment_controller.php"
    public static let payment_request_controller = "payment_request_controller.php"
    public static let reminder_controller = "reminder_controller.php"
    public static let voting_list_controller = "voting_list_controller.php"
    public static let wallet_controller = "wallet_controller.php"
    public static let user_notes_controller = "user_notes_controller.php"
    public static let chat_controller_firebase = "chat_controller_firebase.php"
    public static let visiting_card_controller = "visiting_card_controller.php"
    public static let fast_data_controller = "fast_data_controller.php"
    public static let vendor_referance_controller = "vendor_referance_controller.php"
    public static let additional_company_address_controller = "additional_company_address_controller.php"
};


